### ISSUE TITLE
BUG : Fixes

### ISSUE THREAD

**Issue by glaciar-org** [glaciar-org/Glaciar#2]
**TODO Next Paper:**
 
- [ ] Porqué falta un año en 2017

- [x] Error de Unidad en OD
- [x] Mostrar cuatro estaciones georreferenciadas para Buenos Aires

** IDEAS: **

a) Que el menu aparezca abierto ... 
b) Que los textos estén en castellano (?) ... (Ej "acerca de ... ")
c) Que el logo tenga un link a la home ...

¿Que más?

** DONE: **

- [x] Problema de fechas para DS05
- [x] configuración lateral (borrar al menos layout)
- [x] altura vertical esta desproporcionada
- [x] El datepicker dejo de funcionar

**Comment by glaciar-org** [comment]
Queda mal:

![image](https://user-images.githubusercontent.com/49607964/57978599-3f6c9e00-79e7-11e9-95a8-94e70adb75b6.png)

**Comment by glaciar-org** [comment]
Es por el código:

```
 if (this.chartConfig.scrollbarY) {
     this.scrollbarY = new am4core.Scrollbar()
     chart.scrollbarY = this.scrollbarY
  // chart.scrollbarY.thumb.minHeight = 50
  // chart.scrollbarY.__disabled = false
}
```
